config:
  install_missing_compilers: false
  install_tree:
    root: ${SPACK_ENV}/install_tree
    projections:
      all: '{architecture}/{name}/{version}/{compiler.name}-{compiler.version}/{name}-{version}-{hash:7}'
      ^mpi: '{architecture}/{name}/{version}/{compiler.name}-{compiler.version}__{^mpi.name}-{^mpi.version}/{name}-{version}-{hash:7}'
  url_fetch_method: curl
  build_stage: $tempdir/$user/spack-stage
  misc_cache: $tempdir/cache
  source_cache: $tempdir/var/spack/cache
  test_stage: $tempdir/test
